spring.application.name=auth-service
server.port=8081

spring.datasource.url=jdbc:postgresql://postgres:5432/auth_db
spring.datasource.username=auth_user
spring.datasource.password=auth_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

jwt.secret=rdfko93M8NvW70IhIibp4MqryE6qciSbUCPGlP4JtIfX7wEBEbG7rRQKSN1yj9nT
jwt.expiration=86400000


management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always