spring.application.name=auth-service
server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.cloud.config.enabled=false

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always