spring.application.name=eureka-server
server.port=8761

# Don't register Eureka with itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

eureka.server.enable-self-preservation=false

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always